Lopez-Santi/QEC_code

qec_simulation.py

This will be useful for saving data of large circuits and not having to restart every time.

Added a functionality to be able to skip the iteration step.

---

Implementation Knowledge Base/02. 3 qubit Code Tutorial.ipynb
README.md

formatting updates in second pedagogical notebook

formatting in second pedagogical notebook

---

.gitignore
Implementation Knowledge Base/02. 3 qubit Code Tutorial.ipynb

Add `.DS store` to ignore file, fix a spelling error in a notebook

Minor update

---

Implementation Knowledge Base/02a. Short 3 qubit QEC.ipynb
Implementation Knowledge Base/02b. 3 qubit Restricting Connectivity.ipynb
Implementation Knowledge Base/02c. 3 qubit logical T1 calculation.ipynb
circuit_specific/drawing_helpers.py

Fairly minor cosmetic changes (remove section headings in regular text cells). Small change in `drawing_helpers.py` (TL;DR, return a quantum circuit in case the `draw` doesn't go through the notebook)

Fairly minor cosmetic changes, one function tweak

---

Implementation Knowledge Base/03. Stabilizer Codes and Steane Code.ipynb
circuit_specific/steane_helpers.py

Mostly cosmetic updates to first Steane notebook

Mostly cosmetic updates to first Steane notebook

---

.gitignore
run_tests.py
tests/__init__.py
tests/test_steane.py

Begin the process of adding some unit tests

start to set up some unit tests

---

.gitignore
README.md
check_coverage.sh
tests/test_steane.py

You need to `pip install coverage` or `conda install` it if you want to run `check_coverage.sh`

start to track unit test coverage

---

general_qec/gates.py
tests/test_gates.py

Worked on `gates` module - PEP8 style, `assert` some input conditions, add unit tests (with 100% coverage as of now)

PEP8 style, input checking, and tests

---

tests/test_steane.py

uncomment error-ing steane test so it is not forgotten

uncomment error-ing steane test so it is not forgotten

---

circuit_specific/realistic_three_qubit.py
general_qec/errors.py
general_qec/qec_helpers.py
tests/test_errors.py
tests/test_realistic_codes.py

more PEP8; more unit tests - working on `errors.py`

more PEP8; more unit tests

---

general_qec/errors.py
general_qec/gates.py
tests/test_errors.py

Minor bug fixes in line errored CZ; PEP8; more tests

Minor bug fixes in line errored CZ; PEP8; more tests

---

general_qec/errors.py
tests/test_errors.py
tests/test_errors_rad.py
tests/test_gates.py

Expanded error model test coverage

Expanded error model test coverage

---

general_qec/errors.py
tests/test_errors_prob_rad_cnot.py
tests/test_errors_prob_rad_cz.py
tests/test_errors_rad.py

Error code tests and some DRYing in the error model

Error code tests and some DRYing in the error model

---

general_qec/errors.py
tests/test_errors.py

Very significant DRYing of error model functions. Mostly resolves #42

Very significant DRYing of error model functions

---

general_qec/errors.py
general_qec/qec_helpers.py
tests/test_errors.py
tests/test_errors_prob_rad_cz.py
tests/test_errors_rad.py

100% coverage over `errors.py`; PEP8 enforcement

100% coverage over `errors.py`

---

general_qec/errors.py
tests/test_errors.py

Change "line error codes" to check for whether they should apply Krauss  and/or RAD errors

---

circuit_specific/steane_helpers.py

Still need to work through test logic, but removed crash

Fix crash in simultaneous Steane

---

circuit_specific/steane_helpers.py
general_qec/qec_helpers.py
tests/test_qec_helpers.py
tests/test_steane.py

Speed up of `collapse_ancilla` (from O(n^2) -> O(n)), and associated expanded tests

Speed up of `collapse_ancilla` and associated tests

---

Implementation Knowledge Base/03. Stabilizer Codes and Steane Code.ipynb
Implementation Knowledge Base/03a. Steane Code Restricting Connectivity.ipynb
circuit_specific/steane_helpers.py
tests/test_steane.py

Fix some minor things in the Steane code and start to flow through the changes into the notebooks (no longer need to apply post-fact normalization fixes by hand)

Some Steane code and notebook updates

---

Implementation Knowledge Base/03b. Steane code logical T1 calculation.ipynb
Implementation Knowledge Base/04a. Fault Tolerant Steane Code.ipynb
Implementation Knowledge Base/05. Error Models.ipynb

Minor API and cosmetic updates

Run through the notebooks

---

circuit_specific/steane_helpers.py
general_qec/qec_helpers.py
tests/test_steane_helpers.py

Better Steane tests, some code clean up

Better Steane tests

---

Implementation Knowledge Base/05. Error Models.ipynb

Fixed the typo in the error model, #53

fixed typo in error_models

---

qec_simulation.py

added the nine qubit code the the simulation.py file.

9-qubit code completed in the simulation.py file

---

tests/test_nine_qubit_helpers.py

Tiny change - just starting on unit tests

start tests for the 9 qubit code

---

check_coverage.sh
circuit_specific/steane_helpers.py
general_qec/qec_helpers.py
tests/test_nine_qubit_helpers.py
tests/test_steane_helpers_10q.py
tests/test_steane_helpers_13q.py
tests/test_steane_helpers_grid.py
tests/test_steane_helpers_line.py

Some refactoring to support nine qubit tests

Refactoring to support nine qubit tests

---

Implementation Knowledge Base/{}
check_coverage.sh
circuit_specific/nine_qubit_helpers.py
general_qec/qec_helpers.py
tests/test_nine_qubit_helpers.py

Unit test for 9 qubit code
